# Generated by Django 4.0.4 on 2022-04-30 22:42

import cpf_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('birthday', models.DateField(verbose_name='Aniversário')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Sobre')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='clients_photos', verbose_name='Foto')),
                ('cpf', cpf_field.models.CPFField(blank=True, max_length=14, null=True, verbose_name='cpf')),
                ('rg', models.CharField(blank=True, max_length=14, null=True, verbose_name='RG')),
                ('sexo', models.CharField(choices=[['F', 'Feminino'], ['M', 'Masculino'], ['N', 'Nenhuma das opções']], max_length=1)),
            ],
        ),
    ]
