# Generated by Django 4.0.4 on 2022-05-09 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servidor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssentamentoFuncional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Localizacao', models.CharField(max_length=150)),
                ('obs', models.TextField(blank=True, null=True)),
                ('servidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servidor.servidor', verbose_name='Nome Servidor')),
            ],
        ),
    ]
