# Generated by Django 4.0.4 on 2022-04-30 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_funcional', models.CharField(choices=[('Téc_Admin', 'Tecnico Administrativo'), ('Docente', 'Docente')], max_length=10, verbose_name='Categoria')),
                ('nome', models.CharField(max_length=100, verbose_name='Cargo')),
                ('classe_cargo', models.CharField(choices=[('FUNDAMENTAL', 'Fundamental - Nível - C'), ('MEDIO', 'Médio - Nível - D'), ('SUPERIOR', 'Superior - Nível - E')], max_length=30, verbose_name='Classe Cargo')),
            ],
            options={
                'verbose_name_plural': 'Cargos',
                'ordering': ['classe_cargo', 'nome'],
            },
        ),
    ]
