# Generated by Django 4.0.4 on 2022-05-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assentamento_fucional', '0002_pessoa_situacao_alter_assentamentofuncional_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assentamentofuncional',
            name='status_afd',
            field=models.BooleanField(default=False, verbose_name='Incluido no AFD'),
        ),
    ]
