# Generated by Django 4.0.4 on 2022-05-13 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assentamento_fucional', '0004_rename_localizacao_assentamentofuncional_localizacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArmarioAcervo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Armários',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='FaceArmario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('armario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assentamento_fucional.armarioacervo', verbose_name='Armário')),
            ],
            options={
                'verbose_name_plural': 'Faces Armários',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='PratileiraFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('face', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assentamento_fucional.facearmario', verbose_name='Face Arnário')),
            ],
            options={
                'verbose_name_plural': 'Pratileiras faces',
                'ordering': ['codigo'],
            },
        ),
        migrations.AlterField(
            model_name='assentamentofuncional',
            name='localizacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assentamento_fucional.pratileiraface', verbose_name='Local Assentamento'),
        ),
    ]
