# Generated by Django 4.0.4 on 2022-05-16 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assentamento_fucional', '0005_armarioacervo_facearmario_pratileiraface_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrateleiraFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('face', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assentamento_fucional.facearmario', verbose_name='Face Armário')),
            ],
            options={
                'verbose_name_plural': 'Prateleiras faces',
                'ordering': ['codigo'],
            },
        ),
        migrations.RemoveField(
            model_name='pratileiraface',
            name='face',
        ),
        migrations.AlterModelOptions(
            name='assentamentofuncional',
            options={'ordering': ['nome'], 'verbose_name_plural': 'Assentamentos Funcionais'},
        ),
        migrations.RemoveField(
            model_name='assentamentofuncional',
            name='servidor',
        ),
        migrations.AddField(
            model_name='assentamentofuncional',
            name='categoria_funcional',
            field=models.CharField(choices=[('Téc_Admin', 'Tecnico Administrativo'), ('Docente', 'Docente')], default='Docente', max_length=10, verbose_name='Categoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assentamentofuncional',
            name='matricula',
            field=models.CharField(default='Docente', max_length=10, verbose_name='Matricula SIAPE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assentamentofuncional',
            name='nome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assentamento_fucional.pessoa', verbose_name='Nome Servidor'),
        ),
        migrations.DeleteModel(
            name='Servidor',
        ),
        migrations.AlterField(
            model_name='assentamentofuncional',
            name='localizacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assentamento_fucional.prateleiraface', verbose_name='Local Assentamento'),
        ),
        migrations.DeleteModel(
            name='PratileiraFace',
        ),
    ]
