# Generated by Django 4.0.4 on 2022-04-30 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cargo', '0001_initial'),
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=10, verbose_name='Matricula SIAPE')),
                ('inicio_vinculo', models.DateField(verbose_name='Inicio Vinculo')),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cargo.cargo', verbose_name='Cargo')),
                ('nome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pessoa.person', verbose_name='Nome')),
            ],
            options={
                'verbose_name_plural': 'Servidores',
                'ordering': ['nome'],
            },
        ),
    ]
